.gitignore
Dockerfile
Makefile
src/ur5e_arm.cpp
src/ur5e_arm.hpp

This PR does a number of things
- upgrades the C++ SDK to v0.16
- implements MoveThroughJointPositions
- fixes a latent bug in trajectory smoothing that caused intermittent nonsmooth trajectories due to floating point imprecision
- introduces automatic logging of trajectory and waypoint information to a `.csv` buffer file in a new `logs` directory, for the purpose of easier debugging of trajectories

Upgrade C++ sdk to v0.16 and implement MoveThroughJointPositions

---

src/ur5e_arm.cpp
src/ur5e_arm.hpp

Adds a destructor that calls the ur5e `dashboard->disconnect` [method](https://github.com/UniversalRobots/Universal_Robots_Client_Library/blob/1632f6d2635cb809186939a4e4160f1cb0831937/src/ur/dashboard_client.cpp#L100) from the ur5e library to release the

Add a destructor to the universal robots model

---

src/ur5e_arm.cpp

example output: 
```
t(s),j0,j1,j2,j3,j4,j5,v0,v1,v2,v3,v4,v5
0.2,-3.14159,3.38137e-06,-1.57079,-1.75053,-0.641269,2.50155,0,-0,0,-0,0,0
0.4,-3.11541,3.37789e-06,-1.57079,-1.75053,-0.641269,2.50155,0.174533,-2.31796e-08,1.15898e-07,-4.23855e-07,0,0
0.6,-3.08051,3.37325e-06,-1.57079,-1.75053,-0.641269,2.50155,0.174533,-2.31796e-08,1.15898e-07,-4.23855e-07,0,0
0.8,-3.0456,3.36862e-06,-1.57079,-1.75053,-0.641269,2.50155,0.174533,-2.31796e-08,1.15898e-07,-4.23855e-07,0,0
...
35.4001,2.99325,2.5666e-06,-1.57079,-1.75054,-0.641269,2.50155,0.174533,-2.31796e-08,1.15898e-07,-4.23855e-07,0,0
35.6001,3.02816,2.56197e-06,-1.57079,-1.75054,-0.641269,2.50155,0.174533,-2.31796e-08,1.15898e-07,-4.23855e-07,0,0
35.8001,3.06306,2.55733e-06,-1.57079,-1.75054,-0.641269,2.50155,0.174533,-2.31796e-08,1.15898e- …
```

have trajectories log in absolutes

---

CMakeLists.txt
src/ur5e_arm.cpp
src/ur5e_arm.hpp

Removing unused parameters allows us to turn warning and error flags back on during build

[RSDK-10872] - fix unused parameter build warnings

---

test.cpp

in a previous pr we updated the trajectory file to store timestamps with an absolute time, rather than the relative time diffs that are sent to the arm. Unfortunately, I did not realize there was a test for this function at the time. 
original pr: https://github.com/viam-modules/universal-robots/pull/34
ticket: https://viam.atlassian.net/browse/RSDK-10973

[RSDK-10973] fix trajectory test to use expected time behavior

---

src/kinematics/ur20.json
src/kinematics/ur20.urdf

Added the kinematics files into the repo in  `src/kinematics` - we prefer the `ur20.json` file over the `ur20.urdf`, since that allows us to generate capsules for the geometries associated with each link of the arm.

Add kinematics files for ur20

---

src/ur_arm.cpp

small cleanup stuff, including:
- rename constants from CAPS to kNaming, i.e. `MY_CONST` -> `kMyConst` (google c++ style guide)
- move consts that are used only once into their respective functions
- use `std::chrono::milliseconds` type instead of int (better type representation)
- use `std::this_thread::sleep_for` instead of `usleep` (better portability to non-UNIX systems)
compiles, ~testing on simulator~, works on simulator

[RSDK-10805] cleanup

---

.clang-format
Dockerfile
Makefile
src/ur_arm.cpp

On macOS, Xcode latest is LLVM 19 based. Bringing the internal tools in docker up to the same point will make it easier to get consistent formatting and clang-tidy results, whether things are run in the container or natively.
Meanwhile, tighten up the clang-format settings to more closely align with the C++ SDK, to help stop clang-format from regrouping headers in a way I don't like.
Then put the header grouping back the way I like it.
Also start running clang-format on the tests.
Finally, install `jq` in the docker container since it will need a rebuild anyway and I expect we will want jq after #54 since then we can write meaningful queries against the compilation database to pick out the files that really belong under tidy's careful watch.

[RSDK-11020] Update llvm tools to 19

---

Dockerfile

Apparently, the duplicated line was needed: https://unix.stackexchange.com/questions/776941/apt-add-repository-needs-to-run-twice-on-debian-12

[RSDK-11020] Restore magic add-repository call

---

src/viam/ur/module/ur_arm.cpp

removes duplicate joint positions from the positions provided by the user, which helps the trajectory repo generate valid trajectories. 
additionally returns early from a move call if the arm is already at the goal position and no other waypoints were specified, as well as erroring if we detect an invalid trajectory via a bad `duration`
ticket: https://viam.atlassian.net/browse/RSDK-10979

[RSDK-10979] remove duplicate joint positions and handle invalid durations

---

src/viam/ur/module/ur_arm.cpp

turns out this was pretty easy
I have two ways to solve this atm
1. ignore any small timestamp moves
2. make the final timestep longer to cover the remaining duration of the trajectory
I went with option 1 because option 2 would make the final timestep last between 0.2 to 0.4 seconds long, and I was alittle worried that there might be some weird nuance on the last step that we would lose from having the larger step. its easy enough to switch back if we don't want the if statement/aren't worried about it

[RSDK-11063] handle zero duration errors

---

Makefile

the sim workflow broke a bit when updating the Makefile last time, where `build` now invokes `configure` instead of just making a build directory.
this just makes the build directory for the sim if it doesn't exist.

hotfix: make sim command

---

src/viam/ur/module/test.cpp
src/viam/ur/module/ur_arm.cpp
src/viam/ur/module/ur_arm.hpp

example filenames after change
```sh
2025-07-10T17:13:48.628738Z_arm_joint_positions.csv
2025-07-10T17:13:48.628738Z_trajectory.csv
2025-07-10T17:13:48.628738Z_waypoints.csv
2025-07-10T17:13:50.630518Z_arm_joint_positions.csv
2025-07-10T17:13:50.630518Z_trajectory.csv
2025-07-10T17:13:50.630518Z_waypoints.csv
2025-07-10T17:13:52.632959Z_arm_joint_positions.csv
2025-07-10T17:13:52.632959Z_trajectory.csv
2025-07-10T17:13:52.632959Z_waypoints.csv
2025-07-10T17:13:54.634718Z_arm_joint_positions.csv
2025-07-10T17:13:54.634718Z_trajectory.csv
2025-07-10T17:13:54.634718Z_waypoints.csv
```

[RSDK-11246] use ISO8601 for log names

---

src/viam/ur/module/ur_arm.cpp
src/viam/ur/module/ur_arm.hpp

Each instantiated UR driver for a single module needs to be passed different client-side ports. This commit increments atomic integers for each port to fix this.

[RSDK-10956] allow multiple UR arms on the same robot part

---

CMakeLists.txt
src/viam/ur/module/ur_arm.cpp
src/viam/ur/module/ur_arm.hpp
src/viam/ur/module/utils.cpp
src/viam/ur/module/utils.hpp

The UR arm has its own logger that prints warning logs and higher to stdout by default, however we won't see them since we are running this as a separate process. These changes register a logger callback to use `VIAM_SDK_LOG()` instead.
example output seen on app (level set to `INFO` for testing)
```sh
7/14/2025, 4:45:53 PM info Viam C++ SDK     [module/ur_arm.cpp:200] URCL - /host/build/_deps/universal_robots_client_library-src/src/control/reverse_interface.cpp 219: Robot connected to reverse interface. Ready to receive control commands.   log_ts 2025-07-14T16:45:53.806Z
7/14/2025, 4:45:53 PM info Viam C++ SDK     [module/ur_arm.cpp:200] URCL - /host/build/_deps/universal_robots_client_library-src/src/helpers.cpp 95: SCHED_FIFO OK, priority 99   log_ts 2025-07-14T16:45:53.773Z
7/14/2025, …
```

[rsdk-11005] add URArm log callback

---

src/viam/ur/module/ur_arm.cpp

On L1176, there is an ordered check that first checks `current_state->local disconnect` before setting the `current_state->estop` to `true`, however, in practice, it's possible for an operator to switch to manual mode *before* releasing the estop. 
This leads to a path on L1190 where we try to recovery from an estop despite being in manual mode.
Additionally, some scenarios lead to `shutdown_` being called, clearing the `current_state`, `URArm::reconfigure`'s call to `check_configured_` will throw an error because `current_state` doesn't exist.
Removing the check makes sense since we should still be able to reconfigure our module even when a device is estopped or in manual mode. There's already a check in `shutdown_` that checks for state anyway.

[RSDK-11307] fix unrecoverable case on reconfigure 

---

CMakeLists.txt
Makefile
src/control/external_control.urscript
src/viam/ur/module/ur_arm.cpp
src/viam/ur/module/ur_arm.hpp

First, apologies for the length and complexity here. It was hard to do this one incrementally since it was basically a rewrite of the entire "urcl" side of the driver.
Overall, this thing is more or less working, and it is far _far_ easier to understand the behavior of the system due to log messages like `URArm state transition from state independent(local) to state controlled due to event remote_mode_restored`. There are some rough edges around coming out of local mode that I'm working through with @JohnN193, but I don't expect they will challenge the overall architecture. There are also some small TODO items still to fix up, but, again, none of them are sufficient to prevent review from proceeding in parallel.
Other things that are overall missing:
- There are a number of areas that …

[RSDK-11279] Refactor internal state management and background processing.

---

README.md
meta.json
src/viam/ur/module/ur_arm.cpp

allows for a hardcoded number of packets to be missed before kicking the arm into the disconnected state. 
additionally documents the use of wifi and adds the markdown link to the meta.json, so the docs will now appear on config cards

allow packet loss

---

CMakeLists.txt
Dockerfile
Makefile
meta.json-no-app-image.in
src/viam/ur/module/ur_arm.cpp
src/viam/ur/module/ur_arm_config.hpp.in
src/viam/ur/module/ur_arm_state.cpp
src/viam/ur/module/ur_arm_state.hpp
src/viam/ur/module/ur_arm_state_disconnected.cpp

This is the basic support for direct builds of the driver outside of an appimage. There is no packaging for such a build - you just get an install tree. Optionally, you can turn that into a `module.tar.gz`, which will work on the system where it was built, but not elsewhere, since it has dynamic dependencies on system packages like boost, gRPC, etc.
I've hand tested this on both macOS and linux with some success, and confirmed that I can also still build the appimage way.
As always, I'll leave some comments along the way.

[RSDK-10874] Support building the universal robots driver outside of an appimage

---

src/viam/ur/module/ur_arm.cpp
src/viam/ur/module/ur_arm_state.cpp
src/viam/ur/module/ur_arm_state.hpp
src/viam/ur/module/ur_arm_state_connected.cpp

https://viam.atlassian.net/browse/RSDK-11908
we can now get forces on the arm. here is an example from chris's force testing rig. Unfortunately, the load cells weren't calibrated at the time so we cannot compare numbers, but the forces appear to make sense. 
I also do not have a sense for whether we can determine if the arm is "flat" with this. maybe theres an unexpected jump in forces somewhere but we would need actual data to determine that

[RSDK-11908] get tcp forces

---

src/kinematics/ur20.json
src/kinematics/ur20.urdf

RSDK-11985 - UR20 kinematics file is incorrect
This is so that
```
model.transform(current inputs) == ur20.EndPostion()
```
edit: once this is merged the following would need to be updated for a sanding robot:
1) picture inputs 
2) calibration inputs
3) location of region of interest

RSDK-11985 - UR20 kinematics file is incorrect
