Makefile, meta.json, run.sh, src/ur5e_arm.hpp
I'm fairly sure this is all I need to do to revert back to the AppImage as the entrypoint.  Looking for a sanity check
=> no more mr nice guy

.canon.yaml, src/ur5e_arm.cpp, src/ur5e_arm.hpp
additionally adds a canon profile to use canon instead of naked docker
currently setup to change the max vel/acc for all joints via do command, but we can probably extend this further to setting individual motors
=> add do command to update velocities

CMakeLists.txt, src/control/external_control.urscript, src/ur5e_arm.cpp
updates the universal robotics client, which allows us to reset client communication for the driver.
=> [RSDK-10673] Bump universal robotics client

CMakeLists.txt, Makefile, src/ur5e_arm.cpp, src/ur5e_arm.hpp, test.cpp
[Ticket](https://viam.atlassian.net/browse/RSDK-10701)
Done:
1. Fixes compiler warnings in our code
2. Adds logging so we can see where time is being spent (computing splines vs talking to the arm)
3. Propagate and log IO errors when talking to the arm
4. Fix cases where throwing an exception would kill the background thread
5. Write unique waypoints and trajectory files per run
6. Write the arm joint positions to a file during run 
7. Remove unused code / misleading code
8. Fix integer sign bugs in data written to csv.
9. Shut down all threads when module is shutting down
10. Make the exception safe
TODO in a later PR:
1. [Add CLI for monitoring arm positions in real time](https://github.com/viam-modules/universal-robots/pull/29/files)
2. Upgrade the viam-cpp-sdk
=> RSDK-10701 - Nicks basic cleanup

Makefile
[Ticket](https://viam.atlassian.net/browse/RSDK-10730)
1. support ur5e
2. support ur20
=> RSDK-10730 - Add ursim makefile

CMakeLists.txt, Dockerfile, Makefile, main.cpp, packaging/appimages/universal-robots-aarch64.yml, packaging/appimages/universal-robots-x86_64.yml
I'll leave inline comments explaining the changes.
=> Build system improvements

src/ur_arm.cpp
Should fix failures like this one: https://github.com/viam-modules/universal-robots/actions/runs/15712890863/job/44275291124
=> [RSDK-10974] Fix build on ARM platforms with fp consistency

.gitignore, src/ur_arm.cpp
creates `TrajectoryStatus` enum to replace the `trajectory_running` boolean
=> [RSDK-10798] have move to joint position calls return error on stop

src/ur_arm.cpp, src/viam/ur/module/ur_arm.cpp, src/viam/ur/module/ur_arm.hpp
The data from `actual_qd` appears to be radians per second. 
https://www.universal-robots.com/manuals/EN/HTML/SW10_6/Content/prod-scriptmanual/G5/get_actual_joint_speeds.htm
=> [RSDK-10782] add velocity logging

src/viam/ur/module/ur_arm.cpp, src/viam/ur/module/ur_arm.hpp
This PR checks that the arm model the module is configured for is the same as the connected arm.
=> [RSDK-11004] validate arm model

src/viam/ur/module/ur_arm.cpp, src/viam/ur/module/ur_arm.hpp
This more or less gives the UR arm module the "always rebuild" behavior for reconfigure. I'll leave some comments on the PR as well.
=> [RSDK-10878] Treat reconfiguration for UR arms as always rebuild

Makefile, README.md, meta.json, src/kinematics/ur3e.json, src/viam/ur/module/ur_arm.cpp
It would be great to support another member of the UR family :)
=> add support for UR3e

src/viam/ur/module/ur_arm.cpp
This will need to wait on https://github.com/viamrobotics/rust-utils/pull/151, but it is easy enough to write the code that will use that once it lands in a C++ SDK release.
=> [RSDK-11192] Manage rust-utils memory correctly for OVs

src/viam/ur/module/ur_arm.cpp
this pr handles the case where the arm has been turned off, unplugged, or lost internet connection. This should work with both sim and hardware, though I tested significantly less with sim.
=> [RSDK-10757] handle recovery if the arm was off or disconnected

.clang-tidy, CMakeLists.txt, src/viam/ur/module/ur_arm.cpp, src/viam/ur/module/ur_arm.hpp
- Reconfiguring now stops any actuation
- Getting the end effector position or joint positions does not block on actuation
- Concurrent actuation is prohibited
- The UR SDK is only accessed from the background thread.
=> [RSDK-11056] Fix operation concurrency and reconfiguration

Dockerfile
Does what it says on the box. Relevant diff from C++ SDK: https://github.com/viamrobotics/viam-cpp-sdk/compare/releases/v0.13.2...releases/v0.16.0
=> [RSDK-11411] Upgrade C++ SDK to 0.16.0

src/viam/ur/module/ur_arm.cpp
I'm fairly sure the race isn't actually possible when RDK is driving, because it disallows overlapping actuations. However, it seems wise to me to defend against it within the module, just in case an RDK misbehavior, edge case, or regression somehow allows such through.
The PR introduces an epoch counter to detect whether another move request may have been initiated and completed while the initial move request is still planning.
=> [RSDK-11296] Fix movement edge case race

Dockerfile
By analogy with https://github.com/viam-modules/viam-camera-realsense/compare/main...RSDK-11423
=> Per RSDK-11421 we need to start using a fork for app image builds

src/viam/ur/module/ur_arm.cpp
I happened to notice that the answer to this TODO was actually pretty trivial, since there was already logic to fall back to using the module root, just a little below. I re-ordered the code to make it a little clearer. I also made it so that if you put something that can't convert to a string, that error won't get buried but will get thrown.
=> [RSDK-11299] Cleanup handling of the CSV output path

README.md
If still accurate, would be good to explain these more fully as we do in the old page we're removing from docs in https://github.com/viamrobotics/docs/pull/4485.
Is there a range of acceptable accleration_degs_per_sec2?
And, what's the hardware's max speed?
=> DOCS-4183: Update README.md
